import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/main/Footer";
import Navbar from "@/components/main/Navbar";

export const metadata: Metadata = {
  title: "Alfarsi",
  description: "Generated by Alfarsi Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
